import { Inspection } from "../types/inspection.types"

const date = new Date()

export const mockInspections: Inspection[] = [
  {
    id: "1",
    establishment: {
      name: "Restaurante Bom Sabor",
      address: "Rua das Flores, 123 - São Paulo, SP",
    },
    inspectedAt: date,
    status: "open",
    createdAt: date.toISOString(),
    updatedAt: date.toISOString(),
    inspectorId: "user-1",
    description: "Primeira inspeção de rotina do estabelecimento",
    urgency: "normal",
    needs_imediate_closure: false,
  },
  {
    id: "2",
    establishment: {
      name: "Padaria Doce Manhã",
      address: "Av. Paulista, 1000 - São Paulo, SP",
    },
    inspectedAt: date,
    status: "pending",
    createdAt: date.toISOString(),
    updatedAt: date.toISOString(),
    inspectorId: "user-1",
    description: "Pendente de adequação de estrutura",
    urgency: "high",
    needs_imediate_closure: false,
  },
  {
    id: "3",
    establishment: {
      name: "Mercado Central",
      address: "Rua do Comércio, 45 - Rio de Janeiro, RJ",
    },
    inspectedAt: date,
    status: "open",
    createdAt: date.toISOString(),
    updatedAt: date.toISOString(),
    inspectorId: "user-1",
    description: "Verificar área de armazenamento refrigerado",
    urgency: "normal",
    needs_imediate_closure: false,
  },
  {
    id: "4",
    establishment: {
      name: "Açougue Premium",
      address: "Av. das Carnes, 200 - Belo Horizonte, MG",
    },
    inspectedAt: date,
    status: "pending",
    createdAt: date.toISOString(),
    updatedAt: date.toISOString(),
    inspectorId: "user-1",
    description: "Aguardando documentação de fornecedores",
    urgency: "critical",
    needs_imediate_closure: true,
  },

  // === PASSADAS ===
  {
    id: "5",
    establishment: {
      name: "Lanchonete Rápida",
      address: "Rua Veloz, 78 - São Paulo, SP",
    },
    inspectedAt: date,
    status: "in_accordance",
    createdAt: date.toISOString(),
    updatedAt: date.toISOString(),
    inspectorId: "user-1",
    description: "Inspeção concluída sem irregularidades",
    needs_imediate_closure: false,
  },
  {
    id: "6",
    establishment: {
      name: "Cafeteria Aroma",
      address: "Rua dos Cafés, 15 - Curitiba, PR",
    },
    inspectedAt: date,
    status: "total_closure",
    createdAt: date.toISOString(),
    updatedAt: date.toISOString(),
    inspectorId: "user-1",
    description: "Interdição total por falta de higiene",
    urgency: "critical",
    needs_imediate_closure: true,
  },
  {
    id: "7",
    establishment: {
      name: "Pizzaria Italiana",
      address: "Av. Roma, 500 - São Paulo, SP",
    },
    inspectedAt: date,
    status: "partial_closure",
    createdAt: date.toISOString(),
    updatedAt: date.toISOString(),
    inspectorId: "user-1",
    description: "Interdição parcial da área de preparo",
    urgency: "high",
    needs_imediate_closure: false,
  },
  {
    id: "8",
    establishment: {
      name: "Bar do Zé",
      address: "Rua do Boteco, 99 - Salvador, BA",
    },
    inspectedAt: date,
    status: "in_accordance",
    createdAt: date.toISOString(),
    updatedAt: date.toISOString(),
    inspectorId: "user-1",
    description: "Conformidade total com normas sanitárias",
    needs_imediate_closure: false,
  },
]
